import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import HamburgerNavBar from "./components/navigation/hamburgerNavBar/hamburgerNavBar";
import SiteMap from "@/utils/siteMap";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Jammming - Spotify Playlist App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

			<header className="font-bounce mx-8 mt-6 mb-10 tracking-wider flex flex-auto justify-between">
				<Link className="font-extrabold text-6xl" href={SiteMap.HOME}>jaMMMing</Link>
				<HamburgerNavBar/>
			</header>

        {children}
      </body>
    </html>
  );
}
