import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import HamburgerNavBar from "./components/navigation/hamburgerNavBar/hamburgerNavBar";
import SiteMap from "@/utils/siteMap";


export const metadata: Metadata = {
  title: "Jammming - Spotify Playlist App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className="font-geistSans antialiased">
			<header className="font-bounce mx-3 mt-6 mb-10 tracking-wider flex flex-auto justify-around">
				<Link className="font-extrabold text-6xl" href={SiteMap.HOME}>jaMMMing</Link>
				<HamburgerNavBar/>
			</header>

        {children}
      </body>
    </html>
  );
}
